---
- project:
    queue: kayobe
    templates:
      - openstack-cover-jobs
      - openstack-python3-zed-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - kayobe-tox-ansible-syntax
        - kayobe-tox-ansible
        - kayobe-tox-molecule
        - kayobe-overcloud-ubuntu-jammy
        - kayobe-overcloud-host-configure-ubuntu-jammy
        - kayobe-overcloud-upgrade-ubuntu-focal
        - kayobe-seed-ubuntu-jammy
        - kayobe-seed-upgrade-ubuntu-focal
        - kayobe-seed-vm-ubuntu-jammy
        - kayobe-infra-vm-ubuntu-jammy
    gate:
      jobs:
        - kayobe-tox-ansible-syntax
        - kayobe-tox-ansible
        - kayobe-tox-molecule
        - kayobe-overcloud-ubuntu-jammy
        - kayobe-overcloud-host-configure-ubuntu-jammy
        - kayobe-overcloud-upgrade-ubuntu-focal
        - kayobe-seed-ubuntu-jammy
        - kayobe-seed-upgrade-ubuntu-focal
        - kayobe-seed-vm-ubuntu-jammy
        - kayobe-infra-vm-ubuntu-jammy
    experimental:
      jobs:
        - kayobe-seed-images-ubuntu-jammy
