---
- project:
    templates:
      - openstack-cover-jobs
      - openstack-python3-yoga-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - kayobe-tox-ansible-syntax
        - kayobe-tox-ansible
        - kayobe-tox-molecule
        - kayobe-seed-vm-centos8s
        - kayobe-seed-vm-ubuntu-focal
        - kayobe-infra-vm-centos8s
        - kayobe-infra-vm-ubuntu-focal

    gate:
      queue: kayobe
      jobs:
        - kayobe-tox-ansible-syntax
        - kayobe-tox-ansible
        - kayobe-tox-molecule
        - kayobe-seed-vm-centos8s
        - kayobe-seed-vm-ubuntu-focal
        - kayobe-infra-vm-centos8s
        - kayobe-infra-vm-ubuntu-focal
